name: family_tree
description: Family Tree Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^2.0.0
  firebase_core: ^1.13.1
  auto_route: ^3.2.1
  intl: ^0.17.0
  firebase_storage: ^10.2.8
  image_picker: ^0.8.4+8

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.1
  build_runner:

flutter:

  uses-material-design: true